// Writes reference/parts.md from the part library in src/lego.js, so the list never drifts.
//   node tools/parts-md.cjs
const fs = require('fs');
const path = require('path');
global.window = global;
require(path.resolve(__dirname, '../src/lego.js'));
const LEGO = window.LEGO;
const P = LEGO.PLATE;

const kind = (d) => {
  if (d.kind === 'cyl') return 'round';
  if (d.profile.length === 4) return d.studs.length ? 'box' : 'tile';
  if (d.id === '3044c') return 'ridge';
  return d.profile.length > 6 ? 'curved slope' : 'slope';
};
const studs = (d) => {
  const up = d.studs.filter((s) => !s[3]).length;
  const side = d.studs.length - up;
  return up + (side ? ` + ${side} side` : '');
};

const rows = LEGO.ORDER.map((id) => {
  const d = LEGO.LIB[id];
  return `| ${id} | ${d.label} | ${d.w} × ${d.d} | ${Math.round(d.h / P)} | ${kind(d)} | ${studs(d)} |`;
});
const colors = Object.values(LEGO.COLORS).map((c) => `| \`${c.key}\` | ${c.name} | ${c.hex} |`);

const md = `# Parts and colours in lego.js

Generated by \`node tools/parts-md.cjs\` from the library in \`src/lego.js\`.
Part numbers match the BrickLink catalogue.

## Parts

Width runs along x and depth along y, before rotation. Height is in plates; a brick is three plates.

| No. | Part | Width × depth | Height | Shape | Studs |
|---|---|---|---|---|---|
${rows.join('\n')}

Notes on specific parts
- 3040, 3039 slopes face their low side to -y, studs on the back row.
- 11477, 15068 curved slopes fall towards -y, no studs.
- 3044c double slope, the triangle shows on the ends. Turn it with \`rot: 1\` so the triangle faces forward (that is how the cat's ears are made).
- 87087 brick with a stud on the front face (-y), stud centre 0.7 above the brick bottom.
- 3700, 3701 Technic holes on the long faces, at the same height 0.7.
- 4032, 3941 have an axle hole between the studs.

## Colours

Check in the catalogue that the part is made in the colour you want, see modeling.md.

| Key | BrickLink | Screen colour |
|---|---|---|
${colors.join('\n')}
`;
fs.writeFileSync(path.resolve(__dirname, '../reference/parts.md'), md);
console.log('reference/parts.md', LEGO.ORDER.length, 'parts');
